var __vueify_insert__ = require("vueify/lib/insert-css")
var __vueify_style__ = __vueify_insert__.insert("/**\n * responsive font\n * lastmodify zhancheng\n * 由于UE目前都按375为1:2比例计算，所以默认370px为font-size:100px!important;\n**/\nhtml,\nbody {\n  -webkit-text-size-adjust: none!important;\n}\n@media screen and (min-width: 320px) {\n  html {\n    font-size: 84.375px!important;\n  }\n}\n@media screen and (min-width: 330px) {\n  html {\n    font-size: 87.5px!important;\n  }\n}\n@media screen and (min-width: 340px) {\n  html {\n    font-size: 90.625px!important;\n  }\n}\n@media screen and (min-width: 350px) {\n  html {\n    font-size: 93.75px!important;\n  }\n}\n@media screen and (min-width: 360px) {\n  html {\n    font-size: 96.875px!important;\n  }\n}\n@media screen and (min-width: 370px) {\n  html {\n    font-size: 100.0px!important;\n  }\n}\n@media screen and (min-width: 380px) {\n  html {\n    font-size: 103.125px!important;\n  }\n}\n@media screen and (min-width: 390px) {\n  html {\n    font-size: 106.25px!important;\n  }\n}\n@media screen and (min-width: 400px) {\n  html {\n    font-size: 109.375px!important;\n  }\n}\n@media screen and (min-width: 410px) {\n  html {\n    font-size: 112.5px!important;\n  }\n}\n@media screen and (min-width: 420px) {\n  html {\n    font-size: 115.625px!important;\n  }\n}\n@media screen and (min-width: 430px) {\n  html {\n    font-size: 117.75px!important;\n  }\n}\n@media screen and (min-width: 440px) {\n  html {\n    font-size: 120.875px!important;\n  }\n}\n@media screen and (min-width: 450px) {\n  html {\n    font-size: 124.0px!important;\n  }\n}\n@media screen and (min-width: 460px) {\n  html {\n    font-size: 127.125px!important;\n  }\n}\n@media screen and (min-width: 470px) {\n  html {\n    font-size: 130.25px!important;\n  }\n}\n@media screen and (min-width: 480px) {\n  html {\n    font-size: 133.375px!important;\n  }\n}\n@media screen and (min-width: 490px) {\n  html {\n    font-size: 136.5px!important;\n  }\n}\n@media screen and (min-width: 500px) {\n  html {\n    font-size: 139.625px!important;\n  }\n}\n@media screen and (min-width: 639px) {\n  html {\n    font-size: 142.75px!important;\n  }\n}\n@media screen and (min-width: 719px) {\n  html {\n    font-size: 145.875px!important;\n  }\n}\n@media screen and (max-width: 319px) {\n  html {\n    font-size: 149.0px!important;\n  }\n}\nbody {\n  font-size: 0.12rem;\n}\n")
if (module.hot) {(function () {  module.hot.accept()
  var hotAPI = require("vue-hot-reload-api")
  hotAPI.install(require("vue"), true)
  if (!hotAPI.compatible) return
  module.hot.dispose(function () {
    __vueify_insert__.cache["/**\n * responsive font\n * lastmodify zhancheng\n * 由于UE目前都按375为1:2比例计算，所以默认370px为font-size:100px!important;\n**/\nhtml,\nbody {\n  -webkit-text-size-adjust: none!important;\n}\n@media screen and (min-width: 320px) {\n  html {\n    font-size: 84.375px!important;\n  }\n}\n@media screen and (min-width: 330px) {\n  html {\n    font-size: 87.5px!important;\n  }\n}\n@media screen and (min-width: 340px) {\n  html {\n    font-size: 90.625px!important;\n  }\n}\n@media screen and (min-width: 350px) {\n  html {\n    font-size: 93.75px!important;\n  }\n}\n@media screen and (min-width: 360px) {\n  html {\n    font-size: 96.875px!important;\n  }\n}\n@media screen and (min-width: 370px) {\n  html {\n    font-size: 100.0px!important;\n  }\n}\n@media screen and (min-width: 380px) {\n  html {\n    font-size: 103.125px!important;\n  }\n}\n@media screen and (min-width: 390px) {\n  html {\n    font-size: 106.25px!important;\n  }\n}\n@media screen and (min-width: 400px) {\n  html {\n    font-size: 109.375px!important;\n  }\n}\n@media screen and (min-width: 410px) {\n  html {\n    font-size: 112.5px!important;\n  }\n}\n@media screen and (min-width: 420px) {\n  html {\n    font-size: 115.625px!important;\n  }\n}\n@media screen and (min-width: 430px) {\n  html {\n    font-size: 117.75px!important;\n  }\n}\n@media screen and (min-width: 440px) {\n  html {\n    font-size: 120.875px!important;\n  }\n}\n@media screen and (min-width: 450px) {\n  html {\n    font-size: 124.0px!important;\n  }\n}\n@media screen and (min-width: 460px) {\n  html {\n    font-size: 127.125px!important;\n  }\n}\n@media screen and (min-width: 470px) {\n  html {\n    font-size: 130.25px!important;\n  }\n}\n@media screen and (min-width: 480px) {\n  html {\n    font-size: 133.375px!important;\n  }\n}\n@media screen and (min-width: 490px) {\n  html {\n    font-size: 136.5px!important;\n  }\n}\n@media screen and (min-width: 500px) {\n  html {\n    font-size: 139.625px!important;\n  }\n}\n@media screen and (min-width: 639px) {\n  html {\n    font-size: 142.75px!important;\n  }\n}\n@media screen and (min-width: 719px) {\n  html {\n    font-size: 145.875px!important;\n  }\n}\n@media screen and (max-width: 319px) {\n  html {\n    font-size: 149.0px!important;\n  }\n}\nbody {\n  font-size: 0.12rem;\n}\n"] = false
    document.head.removeChild(__vueify_style__)
  })
  if (!module.hot.data) {
    hotAPI.createRecord("_v-34d5d333", module.exports)
  } else {
    hotAPI.update("_v-34d5d333", module.exports, (typeof module.exports === "function" ? module.exports.options : module.exports).template)
  }
})()}